Mailing dependency injection
Vicctorri/bootcamp-project pull request #7
Opened 2022-01-17 12:11 UTC by Vicctorri

2022-01-17 23:02 UTC, egorbwork requested changes
At this state is not ready. Multiple fixes are required.

2022-01-17 23:02 UTC, egorbwork commented on resources/views/home/contact.blade.php
> +                      {{-- <input type="text" value="{{ old('subject') }}"  class="form-control" placeholder="Subject" name="subject"> --}}
Comment code won't be accepted.

2022-01-17 23:02 UTC, egorbwork commented on app/Services/ContactUsMailer.php
> +    $this->logger->info('conttt info ');
Please fix info message, it should provide value

2022-01-17 23:02 UTC, egorbwork commented on app/Http/Request/ContactRequest.php
> +            'subject' => ['required', 'string', 'min:1', 'in:education,computers,business,science,social,study'],
why do you min:1 here?

2022-01-17 23:02 UTC, egorbwork commented on .gitignore
> +_ide_helper.php
The file was not removed from git.

2022-01-18 21:23 UTC, Vicctorri commented on .gitignore
> +_ide_helper.php
I removed

2022-01-18 21:23 UTC, Vicctorri commented on resources/views/home/contact.blade.php
> +                      {{-- <input type="text" value="{{ old('subject') }}"  class="form-control" placeholder="Subject" name="subject"> --}}
I removed

2022-01-18 21:24 UTC, Vicctorri commented on app/Services/ContactUsMailer.php
> +    $this->logger->info('conttt info ');
Changed

2022-01-19 05:20 UTC, egorbwork approved these changes
Minim necessary changes were applied.

2022-01-20 10:16 UTC, merged